#T1-12. 상위 10개, 하위 10개 차이 Expected Questions
* 문제 : 주어진 데이터에서 상위 10개 국가의 접종률 평균과 하위 10개 국가의 접종률 평균을 구하고, 그 차이를 구해보세요

  (단, 100%가 넘는 접종률 제거, 소수 첫째자리까지 출력)

  데이터셋 : ../input/covid-vaccination-vs-death/covid-vaccination-vs-death_ratio.csv

In [6]:
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/빅분기 실기 연습문제/covid-vaccination-vs-death_ratio.csv')

data.head()

,Unnamed: 0,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
0,0,Afghanistan,AFG,2021-05-11,504502.0,448878.0,55624.0,12,40374668.0,1.111781
1,1,Afghanistan,AFG,2021-05-20,547901.0,470341.0,77560.0,10,40374668.0,1.164941
2,2,Afghanistan,AFG,2021-05-24,573277.0,476367.0,96910.0,10,40374668.0,1.179866
3,3,Afghanistan,AFG,2021-05-26,590454.0,479372.0,111082.0,19,40374668.0,1.187309
4,4,Afghanistan,AFG,2021-05-27,593313.0,479574.0,113739.0,14,40374668.0,1.187809

In [8]:
df_new = data.groupby('country').max()
df_new = df_new.sort_values(by='ratio', ascending=False)

df_new.head()

,Unnamed: 0,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
country,,,,,,,,,
Gibraltar,11368,GIB,2022-03-24,116358.0,42034.0,41228.0,3,33698.0,124.737373
Malta,19948,MLT,2022-03-28,1255851.0,473639.0,466296.0,7,443646.0,106.760570
Niue,22376,NIU,2022-03-13,4161.0,1650.0,1417.0,0,1619.0,101.914762
United Arab Emirates,30916,ARE,2022-03-29,24463702.0,9890318.0,9603499.0,15,10051436.0,98.397065
Portugal,24636,PRT,2022-03-10,22923599.0,9663542.0,9415073.0,297,10150252.0,95.204947

In [9]:
df_new = df_new[df_new['ratio']<=100]

df_new.head()

,Unnamed: 0,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
country,,,,,,,,,
United Arab Emirates,30916,ARE,2022-03-29,24463702.0,9890318.0,9603499.0,15,10051436.0,98.397065
Portugal,24636,PRT,2022-03-10,22923599.0,9663542.0,9415073.0,297,10150252.0,95.204947
Cuba,7263,CUB,2022-03-27,35342367.0,10630665.0,9910237.0,98,11312548.0,93.972331
Chile,6318,CHL,2022-03-22,50302179.0,17859475.0,17346012.0,11447,19275294.0,92.654748
Brunei Darussalam,4562,BRN,2022-03-18,1068468.0,407945.0,404935.0,5,443903.0,91.899582

In [10]:
top10 = df_new['ratio'].head(10).mean()
tail10 = df_new['ratio'].tail(10).mean()


import numpy as np
answer = np.round(top10 - tail10,1)
print(answer)

88.4