#문제1
* 자동차 데이터 셋에서 qsec 컬럼을 Min-Max Scale로 변환 후 0.5보다 큰 값을 가지는 레코드(row) 수를 구하시오

In [41]:
import pandas as pd

df = pd.read_csv('/content/mtcars.csv')
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [43]:
from sklearn.preprocessing import minmax_scale

df['qsec'] = minmax_scale(df['qsec'])

In [44]:
df['qsec']

0     0.233333
1     0.300000
2     0.489286
3     0.588095
4     0.300000
5     0.680952
6     0.159524
7     0.654762
8     1.000000
9     0.452381
10    0.523810
11    0.345238
12    0.369048
13    0.416667
14    0.414286
15    0.395238
16    0.347619
17    0.591667
18    0.478571
19    0.642857
20    0.655952
21    0.282143
22    0.333333
23    0.108333
24    0.303571
25    0.523810
26    0.261905
27    0.285714
28    0.000000
29    0.119048
30    0.011905
31    0.488095
Name: qsec, dtype: float64

In [45]:
answer = len(df[df['qsec'] > 0.5 ])

print(answer)

9

* MinMaxScaler 활용

In [46]:
df = pd.read_csv('/content/mtcars.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [47]:
from sklearn.preprocessing import MinMaxScaler

df['qsec'] = MinMaxScaler(df['qsec'])

df['qsec']

0     MinMaxScaler(feature_range=0     16.46\n1     ...
1     MinMaxScaler(feature_range=0     16.46\n1     ...
2     MinMaxScaler(feature_range=0     16.46\n1     ...
3     MinMaxScaler(feature_range=0     16.46\n1     ...
4     MinMaxScaler(feature_range=0     16.46\n1     ...
5     MinMaxScaler(feature_range=0     16.46\n1     ...
6     MinMaxScaler(feature_range=0     16.46\n1     ...
7     MinMaxScaler(feature_range=0     16.46\n1     ...
8     MinMaxScaler(feature_range=0     16.46\n1     ...
9     MinMaxScaler(feature_range=0     16.46\n1     ...
10    MinMaxScaler(feature_range=0     16.46\n1     ...
11    MinMaxScaler(feature_range=0     16.46\n1     ...
12    MinMaxScaler(feature_range=0     16.46\n1     ...
13    MinMaxScaler(feature_range=0     16.46\n1     ...
14    MinMaxScaler(feature_range=0     16.46\n1     ...
15    MinMaxScaler(feature_range=0     16.46\n1     ...
16    MinMaxScaler(feature_range=0     16.46\n1     ...
17    MinMaxScaler(feature_range=0     16.46\n1     ...
18    MinMaxScaler(feature_range=0     16.46\n1     ...
19    MinMaxScaler(feature_range=0     16.46\n1     ...
20    MinMaxScaler(feature_range=0     16.46\n1     ...
21    MinMaxScaler(feature_range=0     16.46\n1     ...
22    MinMaxScaler(feature_range=0     16.46\n1     ...
23    MinMaxScaler(feature_range=0     16.46\n1     ...
24    MinMaxScaler(feature_range=0     16.46\n1     ...
25    MinMaxScaler(feature_range=0     16.46\n1     ...
26    MinMaxScaler(feature_range=0     16.46\n1     ...
27    MinMaxScaler(feature_range=0     16.46\n1     ...
28    MinMaxScaler(feature_range=0     16.46\n1     ...
29    MinMaxScaler(feature_range=0     16.46\n1     ...
30    MinMaxScaler(feature_range=0     16.46\n1     ...
31    MinMaxScaler(feature_range=0     16.46\n1     ...
Name: qsec, dtype: object

In [48]:
answer = len(df[df['qsec'] > 0.5 ])

print(answer)

TypeError: ignored

* MinMaxScaler() 에서는 minmax_scale()과 다르게 에러 발생하는데 이유는?